<?php

declare(strict_types=1);

use BuiltByBerry\LaravelSwarm\Memory\MemorySnapshot;
use BuiltByBerry\LaravelSwarm\Memory\SnapshotToolCallNormalizer;
use Laravel\Ai\Responses\Data\ToolCall;
use Laravel\Ai\Responses\Data\ToolResult;

/**
 * F2 backward-compat guard for the laravel/ai ^0.8 floor (issue #255).
 *
 * The `tool_calls` snapshot column has no `schema_version`, so a row written
 * under 0.7 and a row written under 0.8 are indistinguishable on the resume
 * read path. The invariant: a pre-upgrade `tool_calls` blob rehydrates and
 * replays byte-identically under 0.8, and `SnapshotToolCallNormalizer` output
 * stays pinned to exactly its five keys regardless of fields added to the
 * upstream `Data\ToolCall` DTO (0.8 added reasoning_id / reasoning_summary /
 * reasoning_encrypted_content for OpenAI ZDR).
 *
 * The fixture is a LITERAL blob committed to disk in the 0.7 shape — not one
 * regenerated by the current normalizer — so the test exercises real
 * pre-upgrade data, not a tautology.
 */
const PINNED_TOOL_CALL_KEYS = ['arguments', 'id', 'name', 'result', 'result_id'];

test('a pre-0.8 tool_calls blob rehydrates byte-identically under 0.8', function (): void {
    $raw = file_get_contents(dirname(__DIR__, 2).'/Fixtures/Persistence/pre_0_8_tool_calls.json');
    expect($raw)->not->toBeFalse();

    /** @var array<int, array<string, mixed>> $persisted */
    $persisted = json_decode($raw, true, flags: JSON_THROW_ON_ERROR);

    $snapshot = MemorySnapshot::fromPersisted(
        payload: ['run_id' => 'run-legacy-1', 'step_index' => 2, 'entries' => []],
        toolCalls: $persisted,
        frozen: true,
    );

    // Rehydration must not transform the persisted tool-call rows in any way:
    // the blob a 0.7 run wrote is the blob a 0.8 resume replays.
    expect($snapshot->toolCalls)->toBe($persisted);

    // And the paired entry still carries exactly the five pinned keys.
    foreach ($snapshot->toolCalls as $entry) {
        expect(collect(array_keys($entry))->sort()->values()->all())->toBe(PINNED_TOOL_CALL_KEYS);
    }
});

test('normalizer pins 0.8 ToolCall output to five keys and drops ZDR reasoning fields', function (): void {
    // A 0.8 ToolCall populated with every new ZDR reasoning field.
    $call = new ToolCall(
        id: 'call_zdr',
        name: 'search_docs',
        arguments: ['query' => 'durable wait'],
        resultId: 'result_zdr',
        reasoningId: 'reason_zdr',
        reasoningSummary: ['step' => 'plan'],
        reasoningEncryptedContent: 'OPAQUE_ENCRYPTED_BLOB',
    );

    $result = new ToolResult(
        id: 'call_zdr',
        name: 'search_docs',
        arguments: ['query' => 'durable wait'],
        result: ['hits' => 3],
        resultId: 'result_zdr',
    );

    $entry = SnapshotToolCallNormalizer::entry($call, $result);

    // Exactly the five pinned keys — no reasoning_id / reasoning_summary /
    // reasoning_encrypted_content leaking into the durable snapshot shape.
    expect(collect(array_keys($entry))->sort()->values()->all())->toBe(PINNED_TOOL_CALL_KEYS);

    // The opaque ZDR blob must never reach persistence under any key.
    expect(json_encode($entry))->not->toContain('OPAQUE_ENCRYPTED_BLOB');

    // A new 0.8 ToolCall normalizes to the same shape a 0.7 run would have
    // written, so old and new rows stay replay-compatible.
    expect($entry)->toBe([
        'id' => 'call_zdr',
        'name' => 'search_docs',
        'arguments' => ['query' => 'durable wait'],
        'result' => ['hits' => 3],
        'result_id' => 'result_zdr',
    ]);
});
