<?php

declare(strict_types=1);

namespace BuiltByBerry\LaravelSwarm\Commands;

use BuiltByBerry\LaravelSwarm\Commands\Concerns\DetachesUnanswerableStdin;
use BuiltByBerry\LaravelSwarm\Commands\Concerns\ResolvesStringConsoleInput;
use Illuminate\Console\GeneratorCommand;
use Symfony\Component\Console\Attribute\AsCommand;

/**
 * Scaffold a deterministic offline swarm agent class.
 *
 * Produces output under `app/Ai/Agents/`. The generated class extends
 * `ScriptedAgent` so existing consumers and published `swarm.agent.stub`
 * customizations keep their established class shape. Model-backed agents are
 * generated by Laravel AI's `make:agent` command instead; this command remains
 * the compatibility path for deterministic offline helpers.
 *
 * Companion command: `make:swarm:swarm` scaffolds the swarm class that
 * composes one or more agents. See `docs/generators.md`.
 */
#[AsCommand(name: 'make:swarm:agent')]
class MakeSwarmAgentCommand extends GeneratorCommand
{
    use DetachesUnanswerableStdin;
    use ResolvesStringConsoleInput;

    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'make:swarm:agent';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a deterministic offline swarm agent (compatibility path; use make:agent for model agents)';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Agent';

    /**
     * Get the stub file for the generator.
     */
    protected function getStub(): string
    {
        return $this->resolveStubPath();
    }

    /**
     * Resolve the fully-qualified path to the stub.
     *
     * Allows applications to override the shipped stub by publishing
     * `stubs/swarm.agent.stub` into the project root.
     */
    protected function resolveStubPath(): string
    {
        $stubFile = 'swarm.agent.stub';

        return file_exists($customPath = $this->laravel->basePath("stubs/{$stubFile}"))
            ? $customPath
            : __DIR__."/../../stubs/{$stubFile}";
    }

    /**
     * Get the default namespace for the class.
     *
     * @param  string  $rootNamespace
     */
    protected function getDefaultNamespace($rootNamespace): string
    {
        return $rootNamespace.'\Ai\Agents';
    }
}
