<?php

declare(strict_types=1);

/**
 * Guards the shipped stubs against re-teaching the deprecated agent marker.
 *
 * v0.23.0 widened Swarm to accept any `Laravel\Ai\Contracts\Agent`, but the fix
 * initially missed the generator stubs and the shipped example swarms: they
 * still declared `@return array<int, \BuiltByBerry\LaravelSwarm\Contracts\Agent>`.
 * That drift is invisible to the rest of the suite, because it only bites in a
 * consumer's project — scaffold a swarm, drop a plain `laravel/ai` agent into
 * `agents()` (the exact thing this release blesses), and *their* PHPStan flags
 * it, with the trail leading back to a stub in this package.
 *
 * A file-level assertion is the right shape here rather than a generator test.
 * The vector memory-tool stub can only be generated by registering a fake
 * companion-package command through the console kernel, and the example swarms
 * are never generated at all — they are copied by the installer. Reading the
 * shipped files covers every stub uniformly, including those paths.
 */
$stubFiles = static function (): array {
    $root = dirname(__DIR__, 2).'/stubs';
    $found = [];

    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS));

    foreach ($iterator as $file) {
        if (! $file->isFile()) {
            continue;
        }

        if (! in_array($file->getExtension(), ['stub', 'php'], true)) {
            continue;
        }

        $found[] = $file->getPathname();
    }

    sort($found);

    return $found;
};

test('no shipped stub references the deprecated swarm Agent marker', function () use ($stubFiles) {
    $offenders = [];

    foreach ($stubFiles() as $path) {
        $contents = file_get_contents($path);

        if ($contents !== false && str_contains($contents, 'BuiltByBerry\LaravelSwarm\Contracts\Agent')) {
            $offenders[] = str_replace(dirname(__DIR__, 2).'/', '', $path);
        }
    }

    expect($offenders)->toBe([], sprintf(
        "These shipped stubs still reference the deprecated agent marker:\n  %s\n".
        'Use Laravel\Ai\Contracts\Agent instead — scaffolded code must not teach the deprecated alias.',
        implode("\n  ", $offenders),
    ));
});

test('every stub declaring an agents() return type names the vendor Agent contract', function () use ($stubFiles) {
    $declaring = [];

    foreach ($stubFiles() as $path) {
        $contents = file_get_contents($path);

        if ($contents !== false && str_contains($contents, '@return array<int, \Laravel\Ai\Contracts\Agent>')) {
            $declaring[] = $path;
        }
    }

    // The four topology stubs plus the shipped example swarms. Asserting a
    // floor (rather than an exact count) keeps this from being a chore every
    // time an example is added, while still failing if the declarations are
    // silently dropped or rewritten.
    expect($declaring)->not->toBeEmpty()
        ->and(count($declaring))->toBeGreaterThanOrEqual(11);
});
